HOORY-6103 add fixes CS form including users embed logic
hoory-com/common-frontend pull request #757
Opened 2023-03-21 09:25 UTC by TaronVardanyan

2023-03-26 18:12 UTC, ArtyomFahradyan requested changes

2023-03-26 18:12 UTC, ArtyomFahradyan commented on ui/components/ChatComponents/RasaMessage/WidgetForm/components/Buttons/index.tsx
> +        !!firstName?.length && !!lastName?.length && !!email?.length;
```suggestion
        !!(firstName?.length && lastName?.length && email?.length);
```

2023-03-26 18:12 UTC, ArtyomFahradyan commented on ui/components/ChatComponents/RasaMessage/WidgetForm/components/Buttons/index.tsx
> +          email === "george@example.com";
why do we need this? we have this only in test.html file which is for local env.

2023-03-26 18:12 UTC, ArtyomFahradyan commented on ui/components/ChatComponents/RasaMessage/WidgetForm/components/Buttons/index.tsx
> +              contactFormResubmitted: isCSRecallAble,
please check if @Horizon733 is fixed default CS button to type  CONNECT_TO_SUPPORT then we don't need this

2023-03-26 18:33 UTC, TaronVardanyan commented on ui/components/ChatComponents/RasaMessage/WidgetForm/components/Buttons/index.tsx
> +          email === "george@example.com";
Unfortunately some of out customers copy and pasting embed code without changing it, this condition was asked from management.

2023-03-26 18:35 UTC, TaronVardanyan commented on ui/components/ChatComponents/RasaMessage/WidgetForm/components/Buttons/index.tsx
> +              contactFormResubmitted: isCSRecallAble,
This contactFormResubmitted prop should also be handled from client side, to avoid of changes from Rasa side. Anyway the logic of CS call at this moment should be global for all our customers and for all cases that we use.

2023-03-26 18:54 UTC, ArtyomFahradyan approved these changes

2023-03-28 12:33 UTC, god-of-javascript approved these changes

2023-03-28 13:02 UTC, merged