HOORY-6325 UI issue on the fields when we insert a data
hoory-com/common-frontend pull request #791
Opened 2023-04-12 08:54 UTC by grigormargaryan

2023-04-12 11:56 UTC, ArtyomFahradyan approved these changes

2023-04-13 07:04 UTC, god-of-javascript requested changes

2023-04-13 07:04 UTC, god-of-javascript commented on ui/components/Editor/EditorMerged/styles.ts
> +} from "../../../../helpers";
@grigormargaryan jan, use `styled-components-helpers`, we will remove this from the common frontend
```suggestion
} from "styled-components-helpers";
```

2023-04-13 07:04 UTC, god-of-javascript commented on ui/components/Editor/EditorMerged/styles.ts
> +  && span[data-testid="mentionText"] {
oh! noo, `data-testid` is not reliable, it can be removed on production.

2023-04-13 08:15 UTC, god-of-javascript approved these changes

2023-04-13 08:15 UTC, merged